### ISSUE TITLE
添加插件失败

### ISSUE THREAD

**Issue by 353776156** [youzan/zan-proxy#26]
每次添加插件失败，提示“Internal Server Error”
插件地址：https://registry.npmjs.org/first-plugs

**Comment by mickeyinfoshan** [comment]
请问是怎么添加的？我这边能添加成功

![image](https://user-images.githubusercontent.com/6109925/42201159-23e2f0a4-7ec9-11e8-8b47-7274b8203ca3.png)

![image](https://user-images.githubusercontent.com/6109925/42201141-19b00432-7ec9-11e8-9e9b-22f30904e891.png)

**Comment by 353776156** [comment]
现在添加插件后，重启zan-proxy，启动失败
当前已是最新版本
开始同步远程规则集
同步远程规则集结束
开始同步远程Host文件
同步远程Host文件结束
(node:843) UnhandledPromiseRejectionWarning: Error: plugin first-plugs not found
    at PluginManager.plugins.storage.get.filter.reduce (/usr/local/lib/node_modules/zan-proxy/dist/App/plugin-manager/index.js:46:23)
    at Array.reduce (<anonymous>)
    at new PluginManager (/usr/local/lib/node_modules/zan-proxy/dist/App/plugin-manager/index.js:40:14)
    at ContainerInstance.getServiceValue (/usr/local/lib/node_modules/zan-proxy/node_modules/_typedi@0.7.3@typedi/ContainerInstance.js:195:21)
    at ContainerInstance.get (/usr/local/lib/node_modules/zan-proxy/node_modules/_typedi@0.7.3@typedi/ContainerInstance.js:43:25)
    at Function.Container.get (/usr/local/lib/node_modules/zan-proxy/node_modules/_typedi@0.7.3@typedi/Container.js:38:36)
    at new Manager (/usr/local/lib/node_modules/zan-proxy/dist/App/manager/index.js:44:49)
    at ContainerInstance.getServiceValue (/usr/local/lib/node_modules/zan-proxy/node_modules/_typedi@0.7.3@typedi/ContainerInstance.js:195:21)
    at ContainerInstance.get (/usr/local/lib/node_modules/zan-proxy/node_modules/_typedi@0.7.3@typedi/ContainerInstance.js:43:25)
    at Object.value (/usr/local/lib/node_modules/zan-proxy/node_modules/_typedi@0.7.3@typedi/decorators/Inject.js:30:42)
(node:843) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:843) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mickeyinfoshan** [comment]
插件的代码有问题，我提供的示例代码不是完整的，省去了如编辑界面的代码，只留下最核心，最简洁的部分

**Comment by mickeyinfoshan** [comment]
后续会提供完整的示例

**Comment by mickeyinfoshan** [comment]
可以先修改文件~/.front-end-proxy/plugins/zanproxy-plugins手动把插件的注册删掉再启动

**Comment by mickeyinfoshan** [comment]
插件的文档已经更新了 https://youzan.github.io/zan-proxy/book/plugin/code.html,
完整的实例可以参考这里：https://github.com/youzan/zan-proxy/tree/master/plugin-examples
