### ISSUE TITLE
4.0.20报错

### ISSUE THREAD

**Issue by libin1991** [youzan/zan-proxy#61]
G:\Code\Vue\vue-tree>zan-proxy
(node:9932) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'G:\tmp\zanproxy.last-update.tmp'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.set (D:\Program Files (x86)\node_modules\zan-proxy\dist\bin\selfUpdate.js:45:22)
    at Object.<anonymous> (D:\Program Files (x86)\node_modules\zan-proxy\dist\bin\selfUpdate.js:55:19)
    at Generator.next (<anonymous>)
    at D:\Program Files (x86)\node_modules\zan-proxy\dist\bin\selfUpdate.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Program Files (x86)\node_modules\zan-proxy\dist\bin\selfUpdate.js:3:12)
    at Object.exports.default (D:\Program Files (x86)\node_modules\zan-proxy\dist\bin\selfUpdate.js:49:25)
    at D:\Program Files (x86)\node_modules\zan-proxy\dist\bin\index.js:35:39
(node:9932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:9932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

G:\Code\Vue\vue-tree>node -v
v8.11.1

G:\Code\Vue\vue-tree>

**Comment by cntsw** [comment]
同样的问题
```bash
$ zan-proxy
(node:7688) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id:                                       2): Error: ENOENT: no such file or directory, open 'C:\tmp\zanproxy.last-update.tmp'
(node:7688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. I                                      n the future, promise rejections that are not handled will terminate the Node.js process                                       with a non-zero exit code.

$ node -v
v8.9.4
```

**Comment by cntsw** [comment]
@mickeyinfoshan  windows下启动好像不能自动建`.front-end-proxy`下的文件
以下是依赖[这次](https://github.com/youzan/zan-proxy/tree/399ae24a3de16dc52fcc35bb5c24e52ae3e2c769)提交报的错误.

```
node dist/bin/index.js
开始同步远程规则集
(node:15928) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: ENOENT: no such file or directory, scandir 'C:\Users\Designer
\.front-end-proxy\rule'
(node:15928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
Node.js process with a non-zero exit code.
```

用`4.0.19`版也是这个问题. 在mac下起是正常的.

**Comment by mickeyinfoshan** [comment]
升级到4.0.22版本 感谢 @cntsw
