### ISSUE TITLE
安装好了各种环境，启动zan-proxy时报错

### ISSUE THREAD

**Issue by DancingC** [youzan/zan-proxy#63]
execute post install 1 scripts...
[1/1] scripts.postinstall zan-proxy@4.0.20 run "node ./scripts/resetDataFile.js"
开始初始化数据...
初始化完成!
[1/1] scripts.postinstall zan-proxy@4.0.20 finished in 279ms
deprecate selfupdate@1.1.0 › president@1.0.0 › windosu@0.1.3 › temp@0.6.0 › rimraf@2.1.4 › graceful-fs@~1 please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
Recently updated (since 2018-07-31): 2 packages (detail see file C:\Users\WEB前端\AppData\Roaming\npm\node_modules\zan-proxy\node_modules\.recently_updates.txt)
  2018-08-04
    → commander@^2.15.1(2.17.0) (08:09:33)
  2018-08-02
    → axios@0.16.2 › follow-redirects@^1.2.3(1.5.2) (02:34:57)
All packages installed (204 packages installed from npm registry, used 14s(network 13s), speed 1.14MB/s, json 188(1.32MB), tarball 13.67MB)
[zan-proxy@4.0.20] link C:\Users\WEB前端\AppData\Roaming\npm\zan-proxy@ -> C:\Users\WEB前端\AppData\Roaming\npm\node_modules\zan-proxy\dist\bin\index.js
[zan-proxy@4.0.20] link C:\Users\WEB前端\AppData\Roaming\npm\zanproxy@ -> C:\Users\WEB前端\AppData\Roaming\npm\node_modules\zan-proxy\dist\bin\index.js

C:\Users\WEB前端>zan-proxy
(node:6812) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\tmp\zanproxy.last-update.tmp'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.set (C:\Users\WEB前端\AppData\Roaming\npm\node_modules\zan-proxy\dist\bin\selfUpdate.js:45:22)
    at Object.<anonymous> (C:\Users\WEB前端\AppData\Roaming\npm\node_modules\zan-proxy\dist\bin\selfUpdate.js:55:19)
    at Generator.next (<anonymous>)
    at C:\Users\WEB前端\AppData\Roaming\npm\node_modules\zan-proxy\dist\bin\selfUpdate.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\WEB前端\AppData\Roaming\npm\node_modules\zan-proxy\dist\bin\selfUpdate.js:3:12)
    at Object.exports.default (C:\Users\WEB前端\AppData\Roaming\npm\node_modules\zan-proxy\dist\bin\selfUpdate.js:49:25)    at C:\Users\WEB前端\AppData\Roaming\npm\node_modules\zan-proxy\dist\bin\index.js:35:39
(node:6812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:6812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mickeyinfoshan** [comment]
参考 #61

**Comment by mickeyinfoshan** [comment]
升级到4.0.22版本
