### ISSUE TITLE
自己写了个插件，但是插件有问题， 导致zan-proxy 启动不起来

### ISSUE THREAD

**Issue by piboye** [youzan/zan-proxy#73]
是不是 zan-proxy 把 插件放到 其它目录了？

重新安装 zan-proxy 也没办法解决：
npm uninstall -g zan-proxy
npm install -g zan-proxy 

出错提示：
zan-proxy
当前已是最新版本
开始同步远程规则集
同步远程规则集结束
开始同步远程Host文件
同步远程Host文件结束
plugin "useragent" has a runtime error. please check it.
Error: plugin useragent not found
    at PluginManager.plugins.storage.get.filter.reduce (/usr/local/lib/node_modules/zan-proxy/dist/App/plugin-manager/index.js:45:27)
    at Array.reduce (<anonymous>)
    at new PluginManager (/usr/local/lib/node_modules/zan-proxy/dist/App/plugin-manager/index.js:41:14)
    at ContainerInstance.getServiceValue (/usr/local/lib/node_modules/zan-proxy/node_modules/typedi/ContainerInstance.js:195:21)
    at ContainerInstance.get (/usr/local/lib/node_modules/zan-proxy/node_modules/typedi/ContainerInstance.js:43:25)
    at Function.Container.get (/usr/local/lib/node_modules/zan-proxy/node_modules/typedi/Container.js:38:36)
    at new Manager (/usr/local/lib/node_modules/zan-proxy/dist/App/manager/index.js:44:49)
    at ContainerInstance.getServiceValue (/usr/local/lib/node_modules/zan-proxy/node_modules/typedi/ContainerInstance.js:195:21)
    at ContainerInstance.get (/usr/local/lib/node_modules/zan-proxy/node_modules/typedi/ContainerInstance.js:43:25)
    at Object.value (/usr/local/lib/node_modules/zan-proxy/node_modules/typedi/decorators/Inject.js:30:42)

**Comment by jituanlin** [comment]
所以你是想初始化zan-proxy的配置吗?
zan-proxy的配置是存放在`~/.frontend-proxy`下面的,把这个文件清空了再试试重新安装.

**Comment by gtgtkiss** [comment]
> cd /.front-end-proxy/plugins 把zanproxy-plugins给清空了，再试试，好坑啊
请问一下，我装的插件进度条每次都卡住，用了https://registry.npm.taobao.org也没用怎么办
