### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by laravelup** [youzan/zan-proxy#75]
sudo npm i -g zan-proxy

开始初始化数据...
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/Users/sunny/.front-end-proxy/certificate'
    at Object.fs.mkdirSync (fs.js:885:18)
    at createDir (/usr/local/lib/node_modules/zan-proxy/scripts/resetDataFile.js:46:12)
    at resetData (/usr/local/lib/node_modules/zan-proxy/scripts/resetDataFile.js:15:5)
    at __dirname (/usr/local/lib/node_modules/zan-proxy/scripts/resetDataFile.js:161:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/zan-proxy/scripts/resetDataFile.js:164:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zan-proxy@4.0.23 postinstall: `node ./scripts/resetDataFile.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zan-proxy@4.0.23 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jituanlin** [comment]
根据错误信息`permission denied`,可以猜想可能是操作文件操作时触发读写权限检查导致的,试试在命令前加个`sudo`试试?

**Comment by cytle** [comment]
加上`--unsafe-perm=true --allow-root`装吧

```bash
sudo npm i -g zan-proxy --unsafe-perm=true --allow-root
```
