### ISSUE TITLE
zan-proxy 启动不了

### ISSUE THREAD

**Issue by guojingwen** [youzan/zan-proxy#78]
参考zp-print-url写了一个插件 一切正常

后来重命名插件并加载， 然后就启动不了了

**Comment by guojingwen** [comment]
zan-proxyguojingwen ~$zan-proxy
开始同步远程规则集
同步远程规则集结束
(node:22392) UnhandledPromiseRejectionWarning: Error: plugin debugger not found
    at PluginManager.plugins.storage.get.filter.reduce (/Users/guojingwen/.nvm/versions/node/v8.10.0/lib/node_modules/zan-proxy/dist/App/plugin-manager/index.js:46:23)
    at Array.reduce (<anonymous>)
    at new PluginManager (/Users/guojingwen/.nvm/versions/node/v8.10.0/lib/node_modules/zan-proxy/dist/App/plugin-manager/index.js:40:14)
    at ContainerInstance.getServiceValue (/Users/guojingwen/.nvm/versions/node/v8.10.0/lib/node_modules/zan-proxy/node_modules/_typedi@0.7.3@typedi/ContainerInstance.js:195:21)
    at ContainerInstance.get (/Users/guojingwen/.nvm/versions/node/v8.10.0/lib/node_modules/zan-proxy/node_modules/_typedi@0.7.3@typedi/ContainerInstance.js:43:25)
    at Function.Container.get (/Users/guojingwen/.nvm/versions/node/v8.10.0/lib/node_modules/zan-proxy/node_modules/_typedi@0.7.3@typedi/Container.js:38:36)
    at new Manager (/Users/guojingwen/.nvm/versions/node/v8.10.0/lib/node_modules/zan-proxy/dist/App/manager/index.js:44:49)
    at ContainerInstance.getServiceValue (/Users/guojingwen/.nvm/versions/node/v8.10.0/lib/node_modules/zan-proxy/node_modules/_typedi@0.7.3@typedi/ContainerInstance.js:195:21)
    at ContainerInstance.get (/Users/guojingwen/.nvm/versions/node/v8.10.0/lib/node_modules/zan-proxy/node_modules/_typedi@0.7.3@typedi/ContainerInstance.js:43:25)
    at Object.value (/Users/guojingwen/.nvm/versions/node/v8.10.0/lib/node_modules/zan-proxy/node_modules/_typedi@0.7.3@typedi/decorators/Inject.js:30:42)
(node:22392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:22392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by guojingwen** [comment]
求支招
